name: Reusable Docker Cache Workflow

on:
  workflow_call:
    inputs:
      dist:
        description: 'Distribution name'
        required: true
        type: string
      python:
        description: 'Python version'
        required: true
        type: string

jobs:
  setup-docker-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        with:
          driver-opts: network=host
          
      - name: Cache Docker layers
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.workflow }}-${{ inputs.dist }}-${{ inputs.python }}-${{ hashFiles('etc/docker/test/*.Dockerfile', '**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.workflow }}-${{ inputs.dist }}-${{ inputs.python }}-
            ${{ runner.os }}-buildx-${{ github.workflow }}-${{ inputs.dist }}-
            ${{ runner.os }}-buildx-${{ github.workflow }}- 